### ISSUE TITLE
`portRange` option requires `port` and `ports` to be set to `null`

### ISSUE THREAD

**Issue by Niek** [unjs/get-port-please#15]
The only way to get `portRange` working is like this:
```js
await getPort({ port: null, ports: [], portRange: [23000, 24000] })
```

This is not very intuitive - if `portRange` is set the other options should be ignored I think.

**Comment by pi0** [comment]
Thanks for the feedback. Hmm i agree specially when user only provides one of this options, others can be automatically disabled. But I would expect to allow `{ port: X, ports: [Y, Z] }` and all 3 being checked. I think we just have to disable **defaults** when either of this options is provided. What do you think?

**Comment by Niek** [comment]
Yes, that seems sensible to me - only use the defaults when neither of these are set.

**Comment by pi0** [comment]
In next major version, when `port` is provided alternative range will be desabled.
