### ISSUE TITLE
Timeout waiting for port

### ISSUE THREAD

**Issue by enkot** [unjs/get-port-please#54]
### Environment

get-port-please v3.0.1
Node.js v16.20.0

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-vdm76f?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.mjs,package-lock.json&title=node.new%20Starter

### Describe the bug

I get 
```sh
Error: Timeout waiting for port 59728 after 4 retries with 500ms interval.
    at async ESMLoader.import (https://stackblitzstartersvdm76f-xrf4.w-credentialless.staticblitz.com/blitz.33975f1d.js:213:4862)
    at async i.loadESM (https://stackblitzstartersvdm76f-xrf4.w-credentialless.staticblitz.com/blitz.33975f1d.js:60:915)
    at async handleMainPromise (https://stackblitzstartersvdm76f-xrf4.w-credentialless.staticblitz.com/blitz.33975f1d.js:168:264)
```
when running `await waitForPort()`.
It happens on [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-vdm76f?file=index.mjs) and MacOS 13.5 (Node 16.20.0, 18.16.1 when running Nitro tests).

**Comment by CodyBontecou** [comment]
Hmm, I'm running into this when attempting to run playwright tests using nuxt/test-utils in a Github Action.

**Comment by kleinpetr** [comment]
Hey I am getting the same error with the nuxt/test-utils in the Github Action, but sometimes locally as well.

```
GetPortError: Timeout waiting for port 38561 after 20 retries with 500ms interval.
 ❯ Module.waitForPort node_modules/.pnpm/get-port-please@3.1.2/node_modules/get-port-please/dist/index.mjs:348:9
```
