### ISSUE TITLE
prefer explicit `port/portRange` even if `random: true` is passed

### ISSUE THREAD

**Issue by davidfirst** [unjs/get-port-please#65]
### Environment

Mac, node 18.

### Reproduction

```
await p.getPort({ random: true, portRange: [5000, 6000]  });
```
output: 

> 63493

### Describe the bug

I get number that are not part of the specified range. (I tried also `alternativePortRange`, same issue).

**Comment by pi0** [comment]
Thanks for report. Should be resolved by https://github.com/unjs/get-port-please/commit/cd4acec1245c7241000cd88f623192709574a370 in next release.
